"""Add employee_id to Sale model

Revision ID: 600b5b273d4f
Revises: 49c5da41ae60
Create Date: 2025-11-28 23:47:36.784483

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '600b5b273d4f'
down_revision = '49c5da41ae60'
branch_labels = None
depends_on = None


def upgrade():
    op.execute('PRAGMA foreign_keys=OFF')
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sale', schema=None) as batch_op:
        batch_op.add_column(sa.Column('employee_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key('fk_sale_employee_id_user', 'user', ['employee_id'], ['id'])

    # ### end Alembic commands ###
    op.execute('PRAGMA foreign_keys=ON')


def downgrade():
    op.execute('PRAGMA foreign_keys=OFF')
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sale', schema=None) as batch_op:
        batch_op.drop_constraint('fk_sale_employee_id_user', type_='foreignkey')
        batch_op.drop_column('employee_id')

    # ### end Alembic commands ###
    op.execute('PRAGMA foreign_keys=ON')
