"""Add StockIn model

Revision ID: 615585e7a095
Revises: 600b5b273d4f
Create Date: 2025-11-29 00:30:35.389958

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '615585e7a095'
down_revision = '600b5b273d4f'
branch_labels = None
depends_on = None


def upgrade():
    op.execute('PRAGMA foreign_keys=OFF')
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stock_in',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stock_in_id', sa.String(length=50), nullable=False),
    sa.Column('date', sa.String(length=50), nullable=False),
    sa.Column('shop_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('supplier', sa.String(length=100), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
    sa.ForeignKeyConstraint(['shop_id'], ['shop.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('stock_in_id')
    )
    # ### end Alembic commands ###
    op.execute('PRAGMA foreign_keys=ON')


def downgrade():
    op.execute('PRAGMA foreign_keys=OFF')
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('stock_in')
    # ### end Alembic commands ###
    op.execute('PRAGMA foreign_keys=ON')
