"""Change Sale.time and StockIn.date to DateTime

Revision ID: 69e058f9db05
Revises: 615585e7a095
Create Date: 2025-11-29 12:07:31.390689

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '69e058f9db05'
down_revision = '615585e7a095'
branch_labels = None
depends_on = None


def upgrade():
    op.execute('PRAGMA foreign_keys=OFF')
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sale', schema=None) as batch_op:
        batch_op.alter_column('time',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.DateTime(),
               existing_nullable=False)

    with op.batch_alter_table('stock_in', schema=None) as batch_op:
        batch_op.alter_column('date',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.DateTime(),
               existing_nullable=False)

    # ### end Alembic commands ###
    op.execute('PRAGMA foreign_keys=ON')


def downgrade():
    op.execute('PRAGMA foreign_keys=OFF')
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stock_in', schema=None) as batch_op:
        batch_op.alter_column('date',
               existing_type=sa.DateTime(),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)

    with op.batch_alter_table('sale', schema=None) as batch_op:
        batch_op.alter_column('time',
               existing_type=sa.DateTime(),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)

    # ### end Alembic commands ###
    op.execute('PRAGMA foreign_keys=ON')
